# Header
menu:
  Home: /
  Archives: /archives
  白菜: /tags/baicai
  猪肉: /tags/zhurou
#rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.ico
